:blank: pass:[ +]

= Week 1- Account Setup

:sectnums!:

== Overview

You have three required tasks and one optional task to complete this week,
as well as the assigned readings. Don't wait until the end of the week to
begin working on these tasks!

* Sign up for a free GitHub.com account.
* Sign up for a free Slack account and optionally install software on your desktop and/or
mobile device.
* Sign up for an Amazon Web Services account.
* (Optional) Take the _Try Git_ online class.

:sectnums:
==  GitHub.com account

Sign up for a free GitHub account by going to https://github.com and clicking
the `Sign Up` button. You are welcome to use an existing personal GitHub account if have one. *Please fill this [Information Form](https://forms.gle/DsAA2p1FmjRTex5TA) so I can to add you to our github account.* Every assignment in this class is submitted using GitHub repositories.

== Slack account
* Sign up for a free Slack account at https://join.slack.com/t/leanonproject/shared_invite/enQtNzM5MzI5ODU3NTU0LTdmNWIwMGNkYzRjODc1ZjRhNzM3YjJlNGFjOGFmYzNkM2QzNDRiMDFkNzZkMzNlMDU1NTNlZDNiYTJjYzc4M2Y
* Join the *#software-dev* Channel - This will be the official chat forum for the class.

You can access Slack using a web browser or you can download a desktop application
(https://slack.com/downloads). Slack is also available as an app for your mobile
device. This course doesn't teach you how to use Slack, but it's pretty easy
to figure out. Just go to the Slack website and click on the `Getting Started` link
to learn the basics.

We will use Slack as a group communication tool throughout the course. If you have a
question or encounter a problem while working with a tool, you should ask your
question on Slack first. 


== _Try Git_ (optional)

The _Try Git_ online class provides a quick introduction to Git where you can
play with some of the basic commands. Students that have not used Git before
are *strongly encouraged* to take this 15-minute class. The class is located at
https://try.github.io


== First Commit
Assignment Invitation is here:
https://classroom.github.com/a/ssQCc_6F

For help with using github classroom watch this video:
http://www.youtube.com/watch?v=euUdiVU0A_k&t=4m21s

Once you accept the invitation and clone the repo, follow these steps:
* Create a directory at the top level called “ux”
* Create a file called “index.html”
* Paste the Simple html code in the file
```
<!DOCTYPE html>
<html>
<body>

<h1>My First Commit</h1>

</body>
</html>
```

* Delete the content of the README file and you full name (as Heading) and “First Commit” as body.
* Add and commit the file and directory to git using this git comment
“BSSD - Test Commit”
* Push to remote repo on github.




`Credit - Jason Baker <bake2352@stthomas.edu>`


